# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56cfc3bc74a72b789c6ce6068f9b3791ec3a5a16870b8331ecf5db0f24ff686fb942328bba8002d60fadeec77a7aaecc8cd2ea405d9e77caef1f66c8ad3e2b65

test:
  secret_key_base: 12ecd89e0ff11e4902a6dff9402f91efac2b8fbf324d0aa011931686f2f18108d47b9a399701208ec067e2f6ea5fb695d7f37db736e24ce68d57d821f22dd6fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
